### ISSUE TITLE
Error: unable to resolve dependency tree

### ISSUE THREAD

**Issue by AurelBdl** [bidah/uni-stack#3]
Hey !

I'm getting this error during packages installation while trying to init a new app using "npx create-uni-app"
`
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: babiffle@1.0.0
npm ERR! Found: @tanstack/react-query@5.25.0
npm ERR! node_modules/@tanstack/react-query
npm ERR!   @tanstack/react-query@"^5.20.5" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @tanstack/react-query@"^4.18.0" from @trpc/react-query@10.45.1
npm ERR! node_modules/@trpc/react-query
npm ERR!   @trpc/react-query@"^10.45.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`
I tried on Windows and MacOs environments and both failed for the same reason.

**Comment by bidah** [comment]
Hey, not sure how to solve this. One thing you could try is that the CLI pick up on of your package managers. Seems its trying with npm. Why don't you give it a go with https://bun.sh/ and see if it works? If you have bun installed the CLI will pick it up first.
